version: '3.8'

services:
  nginx:
    depends_on:
      - backend
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env

  frontend:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - ./frontend:/app